/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package testapp;

import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * Author: Kaylee Springer
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        
        /*Written by Kaylee Springer*/
        //String of Course Names
        String[] courses = {"CMPSC-206 Web Applications 1", "CMPSC-306 Web Applications 2", "CMPSC-255 Introduction to Networks", "CMPSC-200 Virtual Worlds", "CMPSC-202 Programming I ", "CMPSC-203 Programming II", "CMPSC-345 Computer Systems & Organization", "CMPSC-311 Data Structures & Algorithms", "MATH-200 Discrete Mathematics", "RELST-266 Suffering & Death", "CMPSC-390 Software Engineering", "CMPSC-309 Issues in Computing", "BIOL-117 Exercise Physiology", "CMPSC-321 Databases", "ART-119 Digital Imagery", "Comms 221 Digital Video Production", "MATH-135 Introduction to Statistics", "ART-111 Intro to Film Analysis", "CMPSC-301 Operating Systems", "ART 220: Graphic Design II", "COMM-205 Mediated Message Production", "ART 322: Advertising in Marketing", "BIOL 213: Interactions in the Environment", "CMPSC-360 Usability and Design", "CHEM 331: Physical Chemistry", "PSYCH-101 Introduction to Psychology", "CHEM-111 General Chemistry", "MATH 202: Calculus with Analytic Geometry", "HIST-103 U.S. History to 1877", "COMM 220: Digital Audio Production", "Psych-200 child development", "Psych-199 lifespan development", "Psych-204 abnormal psychology", "MKTG 355 Digital Marketing", "BIOL-206 microbiology", "MGMT 370 IT Management", "BIOL-202 Human Anatomy", "ENGL 208: Study of Rhetoric", "BIOL-203 Human physiology", "CMPSC-260 Clojure"};
        ClassList1.setModel(new DefaultComboBoxModel<>(courses));
        
        //String[] appointments = new String[5];
        String[] appointments = {"No Appointments"};
        AppointmentList.setModel(new DefaultComboBoxModel<>(appointments));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        logout = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClassList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        AppointmentList = new javax.swing.JList<>();
        Notifications = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BottomAppointment = new javax.swing.JPanel();
        BottomAppoint = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        BottomClass = new javax.swing.JLabel();
        ClassButton = new javax.swing.JButton();
        AppointmentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(171, 198, 231));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Account");

        logout.setActionCommand("Logout");
        logout.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 51, 51));
        logout.setLabel("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        logout.getAccessibleContext().setAccessibleName("Logout");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 130));

        jPanel2.setBackground(new java.awt.Color(171, 198, 231));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel3.setText("FindMyTutor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel3)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel3)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 650, -1));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));

        jScrollPane1.setViewportView(ClassList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 360, 110));

        AppointmentList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(AppointmentList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 360, 120));

        Notifications.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Notifications");

        javax.swing.GroupLayout NotificationsLayout = new javax.swing.GroupLayout(Notifications);
        Notifications.setLayout(NotificationsLayout);
        NotificationsLayout.setHorizontalGroup(
            NotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NotificationsLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel5)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        NotificationsLayout.setVerticalGroup(
            NotificationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NotificationsLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        getContentPane().add(Notifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 200, 50));

        BottomAppointment.setBackground(new java.awt.Color(255, 255, 255));

        BottomAppoint.setText("Appointments");
        BottomAppoint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BottomAppointKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout BottomAppointmentLayout = new javax.swing.GroupLayout(BottomAppointment);
        BottomAppointment.setLayout(BottomAppointmentLayout);
        BottomAppointmentLayout.setHorizontalGroup(
            BottomAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BottomAppointmentLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(BottomAppoint)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        BottomAppointmentLayout.setVerticalGroup(
            BottomAppointmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BottomAppointmentLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(BottomAppoint)
                .addContainerGap())
        );

        getContentPane().add(BottomAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        BottomClass.setText("Classes");
        BottomClass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BottomClassMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(BottomClass)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(BottomClass)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 200, 50));

        ClassButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        ClassButton.setText("Classes");
        ClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ClassButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        AppointmentButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        AppointmentButton.setText("Appointments");
        AppointmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AppointmentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        pack();
    }// </editor-fold>                        

    
    //This section of code was written By Kaylee Springer
    /*********************************************************/
    //Code to Move to Classes Page
    private void ClassButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(rootPane, jList1.getSelectedValue());
        //Opens Course Page
        CourseScreen classScreen = new CourseScreen();
        classScreen.show();//display CourseScreen
        dispose(); //Close current fram after opening
        
    }                                           

    private void AppointmentButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        //Opens Course Page
        AppointmentScreen appoint = new AppointmentScreen();
        appoint.show();//display CourseScreen
        dispose(); //Close current fram after opening
        
    }                                                 

    private void BottomClassMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        //Opens Course page from bottom tab
        CourseScreen classScreen = new CourseScreen();
        classScreen.show();//display CourseScreen
        dispose(); //Close current fram after opening
    }                                        

    private void BottomAppointKeyPressed(java.awt.event.KeyEvent evt) {                                         
        // TODO add your handling code here:
        //Opens Appointment Page from bottom tab
        AppointmentScreen appoint = new AppointmentScreen();
        appoint.show();//display CourseScreen
        dispose(); //Close current fram after opening
    }                                        

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        LoginScreen logout = new LoginScreen();
        logout.show();//display CourseScreen
        dispose(); //Close current fram after opening
    }                                      

    
    
    /********************************************************/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton AppointmentButton;
    private javax.swing.JList<String> AppointmentList;
    private javax.swing.JLabel BottomAppoint;
    private javax.swing.JPanel BottomAppointment;
    private javax.swing.JLabel BottomClass;
    private javax.swing.JButton ClassButton;
    private javax.swing.JList<String> ClassList1;
    private javax.swing.JPanel Notifications;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Button logout;
    // End of variables declaration                   
}
